//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/RobotService/OperatorMessage")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/RobotService/OperatorMessage", IsNullable=false)]
public partial class OperatorMessage {
    
    private OperatorMessageHeader headerField;
    
    private object itemField;
    
    /// <remarks/>
    public OperatorMessageHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Message", typeof(Message), Namespace="http://tempuri.org/RobotService/FrontEndMessage")]
    [System.Xml.Serialization.XmlElementAttribute("DummyOperatorElementType", typeof(OperatorMessageDummyOperatorElementType))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/RobotService/OperatorMessage")]
public partial class OperatorMessageHeader {
    
    private int messageTypeField;
    
    /// <remarks/>
    public int MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/RobotService/FrontEndMessage")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/RobotService/FrontEndMessage", IsNullable=false)]
public partial class Message {
    
    private MessageHeader headerField;
    
    private object itemField;
    
    /// <remarks/>
    public MessageHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Config", typeof(MessageConfig))]
    [System.Xml.Serialization.XmlElementAttribute("Data", typeof(MessageData))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/RobotService/FrontEndMessage")]
public partial class MessageHeader {
    
    private string messageTypeField;
    
    private string messageContentField;
    
    /// <remarks/>
    public string MessageType {
        get {
            return this.messageTypeField;
        }
        set {
            this.messageTypeField = value;
        }
    }
    
    /// <remarks/>
    public string MessageContent {
        get {
            return this.messageContentField;
        }
        set {
            this.messageContentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/RobotService/FrontEndMessage")]
public partial class MessageConfig {
    
    private string dummyConfigElementField;
    
    /// <remarks/>
    public string DummyConfigElement {
        get {
            return this.dummyConfigElementField;
        }
        set {
            this.dummyConfigElementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/RobotService/FrontEndMessage")]
public partial class MessageData {
    
    private string dummyDataElementField;
    
    /// <remarks/>
    public string DummyDataElement {
        get {
            return this.dummyDataElementField;
        }
        set {
            this.dummyDataElementField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/RobotService/OperatorMessage")]
public partial class OperatorMessageDummyOperatorElementType {
    
    private string dummyOperatorElementTypeDataItemField;
    
    /// <remarks/>
    public string DummyOperatorElementTypeDataItem {
        get {
            return this.dummyOperatorElementTypeDataItemField;
        }
        set {
            this.dummyOperatorElementTypeDataItemField = value;
        }
    }
}
